CREATE DATABASE TIENDAHM;
USE TIENDAHM;

CREATE TABLE CATEGORIAS (
ID_CATEGORIA INT NOT NULL AUTO_INCREMENT,
CATEGORIA_ROPA VARCHAR(20),
CONSTRAINT PK_CATEGORIAS PRIMARY KEY(ID_CATEGORIA));

SELECT * FROM CATEGORIAS;

INSERT INTO CATEGORIAS VALUES (1, 'Hombre');
INSERT INTO CATEGORIAS VALUES (2, 'Mujer');
INSERT INTO CATEGORIAS VALUES (3, 'Niños');

CREATE TABLE MARCA (
ID_MARCA INT NOT NULL AUTO_INCREMENT,
NOMBRE_MARCA VARCHAR(20),
CONSTRAINT PK_MARCA PRIMARY KEY(ID_MARCA));

INSERT INTO MARCA VALUES (1, 'H&M');

CREATE TABLE PRODUCTO (
ID_PRODUCTO INT NOT NULL AUTO_INCREMENT,
ID_CATEGORIA INT NOT NULL,
ID_MARCA INT NOT NULL,
NOMBRE_PRENDA VARCHAR(30) NOT NULL,
PRECIO DECIMAL(9,2) NOT NULL,
TALLA VARCHAR(3) NOT NULL,
CANTIDAD INT NOT NULL,
CONSTRAINT PK_PRODUCTO PRIMARY KEY(ID_PRODUCTO),
CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIAS (ID_CATEGORIA),
CONSTRAINT FK_PRODUCTO_MARCAS FOREIGN KEY(ID_MARCA) REFERENCES MARCA (ID_MARCA));

CREATE TABLE PROVINCIAS (
ID_PROVINCIA INT NOT NULL AUTO_INCREMENT,
NOMBRE_PROVINCIA VARCHAR(15),
CONSTRAINT PK_PROVINCIAS PRIMARY KEY(ID_PROVINCIA));

SELECT * FROM PROVINCIAS;

CREATE TABLE USUARIOS(
USUARIO_ID INT NOT NULL AUTO_INCREMENT,
CEDULA VARCHAR(15),
ID_PROVINCIA INT NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
PRIMER_APELLIDO VARCHAR(20) NOT NULL,
SEGUNDO_APELLIDO VARCHAR(20) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
TELEFONO INT NOT NULL,
CONTRASENA VARCHAR(15) NOT NULL,
CONSTRAINT PK_USUARIOS PRIMARY KEY(USUARIO_ID),
CONSTRAINT FK_PRODUCTO_PROVINCIA FOREIGN KEY(ID_PROVINCIA) REFERENCES PROVINCIAS (ID_PROVINCIA));

INSERT INTO USUARIOS (CEDULA, ID_PROVINCIA, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, EMAIL, 
TELEFONO, CONTRASENA) VALUES ('11111111', 3, 'Brayan', 'Rivas',  'López', 'brayan@gmail.com', 22222222, '1234'); 

INSERT INTO USUARIOS (CEDULA, ID_PROVINCIA, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, EMAIL, 
TELEFONO, CONTRASENA) VALUES ('11111112', 3, 'Valeria', 'Zeledón', 'Salazar', 'valeria@gmail.com', 22222522, '1234'); 









 