CREATE DATABASE TIENDAHM;
USE TIENDAHM;

CREATE TABLE TIPO_PRENDA (
    ID_TIPO INT NOT NULL AUTO_INCREMENT,
    NOMBRE_TIPO VARCHAR(50) NOT NULL,
    CONSTRAINT PK_TIPO_PRENDA PRIMARY KEY(ID_TIPO)
);

CREATE TABLE CATEGORIAS (
ID_CATEGORIA INT NOT NULL AUTO_INCREMENT,
CATEGORIA_ROPA VARCHAR(20),
CONSTRAINT PK_CATEGORIAS PRIMARY KEY(ID_CATEGORIA)
);

SELECT * FROM CATEGORIAS;

INSERT INTO CATEGORIAS VALUES (1, 'Hombre');
INSERT INTO CATEGORIAS VALUES (2, 'Mujer');
INSERT INTO CATEGORIAS VALUES (3, 'Niños');

CREATE TABLE MARCA (
ID_MARCA INT NOT NULL AUTO_INCREMENT,
NOMBRE_MARCA VARCHAR(20),
CONSTRAINT PK_MARCA PRIMARY KEY(ID_MARCA)
);

INSERT INTO MARCA VALUES (1, 'H&M');

CREATE TABLE PRODUCTOS (
ID_PRODUCTO INT NOT NULL AUTO_INCREMENT,
ID_TIPO INT NOT NULL,
ID_CATEGORIA INT NOT NULL,
ID_MARCA INT NOT NULL,
NOMBRE_PRENDA VARCHAR(30) NOT NULL,
PRECIO DECIMAL(9,2) NOT NULL,
TALLA VARCHAR(3) NOT NULL,
CANTIDAD INT NOT NULL,
CONSTRAINT PK_PRODUCTO PRIMARY KEY(ID_PRODUCTO),
CONSTRAINT FK_PRODUCTO_TIPO FOREIGN KEY(ID_TIPO) REFERENCES TIPO_PRENDA (ID_TIPO),
CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIAS (ID_CATEGORIA),
CONSTRAINT FK_PRODUCTO_MARCAS FOREIGN KEY(ID_MARCA) REFERENCES MARCA (ID_MARCA)
);


CREATE TABLE USUARIOS(
USUARIO_ID INT NOT NULL AUTO_INCREMENT,
CEDULA VARCHAR(15),
NOMBRE VARCHAR(20) NOT NULL,
PRIMER_APELLIDO VARCHAR(20) NOT NULL,
SEGUNDO_APELLIDO VARCHAR(20) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
TELEFONO INT NOT NULL,
CONTRASENA VARCHAR(15) NOT NULL,
CONSTRAINT PK_USUARIOS PRIMARY KEY(USUARIO_ID)
);

INSERT INTO USUARIOS (CEDULA, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, EMAIL, 
TELEFONO, CONTRASENA) VALUES ('11111111', 'Brayan', 'Rivas',  'López', 'brayan@gmail.com', 22222222, '1234'); 

INSERT INTO USUARIOS (CEDULA, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, EMAIL, 
TELEFONO, CONTRASENA) VALUES ('11111112', 'Valeria', 'Zeledón', 'Salazar', 'valeria@gmail.com', 22222522, '1234'); 









 